services:
  subscriber-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Subscriber_345!
      - ACCEPT_EULA=Y
    ports:
      - "1635:1433"
    volumes:
      - subscriber-db-data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  subscriber-db-data: