FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["NewsletterService/NewsletterService.csproj", "NewsletterService/"]
COPY ["ArticleQueue/ArticleQueue.csproj", "ArticleQueue/"]
COPY ["MonitorService/MonitorService.csproj", "MonitorService/"]
COPY ["Shared/Shared.csproj", "Shared/"]
RUN dotnet restore "NewsletterService/NewsletterService.csproj"
COPY . .
WORKDIR "/src/NewsletterService"
RUN dotnet build "./NewsletterService.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./NewsletterService.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "NewsletterService.dll"]
