CREATE TABLE Articles
(
    ArticleId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Title NVARCHAR(MAX) NOT NULL,
    Contents NVARCHAR(MAX) NOT NULL,
    PublishingDate DATETIME2 NOT NULL,
    AuthorId UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_Articles_Authors FOREIGN KEY (AuthorId)
        REFERENCES Authors (AuthorId)
        ON DELETE CASCADE
);

CREATE TABLE Authors
(
    AuthorId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    AuthorName NVARCHAR(100) NOT NULL,
    AuthorLastName NVARCHAR(100) NOT NULL
);