name: workflow.yml
on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  integration:
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.semver.outputs.version }} 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate results of code analysis

      - name: Application Version
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          bump_each_commit: true # Automatically bump version for each commit

      - name: Build
        run: dotnet build
  
  delivery:
    runs-on: ubuntu-latest
    needs: integration
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate results of code analysis
      
      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build and Push Docker image (Article-Service)
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/article-service:${{ needs.integration.outputs.semver }} \
            -f ArticleService/Dockerfile \
            .
          docker push ghcr.io/${{ github.repository_owner }}/article-service --all-tags

      # Build the Docker image
      - name: Build and Push Docker image (Comment-Service)
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/comment-service:${{ needs.integration.outputs.semver }} \
            -f CommentService/Dockerfile \
            .
          docker push ghcr.io/${{ github.repository_owner }}/comment-service --all-tags
          
      # Build the Docker image
      - name: Build and Push Docker image (Draft-Service)
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/draft-service:${{ needs.integration.outputs.semver }} \
            -f DraftService/Dockerfile \
            .
          docker push ghcr.io/${{ github.repository_owner }}/draft-service --all-tags
          
      # Build the Docker image
      - name: Build and Push Docker image (Newsletter-Service)
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/newsletter-service:${{ needs.integration.outputs.semver }} \
            -f NewsletterService/Dockerfile \
            .
          docker push ghcr.io/${{ github.repository_owner }}/newsletter-service --all-tags
          
      # Build the Docker image
      - name: Build and Push Docker image (Profanity-Service)
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/profanity-service:${{ needs.integration.outputs.semver }} \
            -f ProfanityService/Dockerfile \
            .
          docker push ghcr.io/${{ github.repository_owner }}/profanity-service --all-tags
          
      # Build the Docker image
      - name: Build and Push Docker image (Publisher-Service)
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/publisher-service:${{ needs.integration.outputs.semver }} \
            -f PublisherService/Dockerfile \
            .
          docker push ghcr.io/${{ github.repository_owner }}/publisher-service --all-tags